server:
    port: 12000

jwt:
    secret: lbwnb!_O!qi_dong!
    expired: 3600000

uploadPath: /Users/horacegriffin/Documents/000-code/010-java/cyzy-spring-boot/upload/

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/db_4_had1szz?useUnicode=true&charset=utf-8
        username: root
        password: 12345678
    web:
        resources:
            static-locations: classpath:/static/, file:${uploadPath}
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
